/**************************************************************************//**
 * @file     ConfigIO.h
 * @version  V1.00
 * $Revision: 1 $
 * $Date: 14/09/25 11:00a $
 * @brief    Header file of IO configuration.
 *           This file could be generated by NuKeilIDE tool. 
 *
 * Copyright (C) 2014 Nuvoton Technology Corp. All rights reserved.
 ******************************************************************************/

#ifndef _CONFIGIO_H_
#define _CONFIGIO_H_

#include "Platform.h"

//%{CodeGen_Block_Start}
#define KEY_DEBOUNCE_TIME		(0.2000)	// unit:s
#define KEY_PRESS_TIME			(3.0000)	// unit:s

//------------------------------------------------------------------------------------------------//
// Configurations of Matrix Keys
//------------------------------------------------------------------------------------------------//
// Keypad Matrix Mapping
//
////			(Input)
//			GPA.10	GPA.11
// (Output)	  |  	  |
// GPB.8 -	Key1	Key2
// GPB.9 -	Key3	Key4


#define MATRIX_INPUT_PINS_COUNT     (2)	// in:2, out:2
#define MATRIX_OUTPUT_PINS_COUNT    (2)
#define MATRIX_KEY_COUNT            (MATRIX_INPUT_PINS_COUNT*MATRIX_OUTPUT_PINS_COUNT)

#define MATRIX_PORTA_INPUT_PINS_MASK	(BIT10|BIT11)
#define MATRIX_PORTA_OUTPUT_PINS_MASK	(0)	// BIT1~BITn

#define MATRIX_PORTB_INPUT_PINS_MASK	(0)
#define MATRIX_PORTB_OUTPUT_PINS_MASK	(BIT8|BIT9)	// BIT1~BITn

//------------------------------------------------------------------------------------------------//
// Configurations of Input Keys
//------------------------------------------------------------------------------------------------//
#define TRIGGER_KEY_COUNT	(0)

//TRIGGER_PORT
#define TRIGGER_PORTA_PINS_MASK		(0)
#define TRIGGER_PORTB_PINS_MASK		(0)

//------------------------------------------------------------------------------------------------//
// Configurations of Output Keys
//------------------------------------------------------------------------------------------------//
#define OUT_KEY_COUNT		(0)

//OUTPUT_PORT
#define OUTPUT_PORTA_PINS_MASK		(0)
#define OUTPUT_PORTB_PINS_MASK		(0)

extern void OutputPin_Set(GPIO_T *pPort, UINT16 u16PinMask, UINT8 u8Value);


//------------------------------------------------------------------------------------------------//
// Configurations of KEY (key matrix) Handlers
//------------------------------------------------------------------------------------------------//
#define KEYR		0x10000000
#define KEYF		0x20000000
#define KEYP		0x40000000

//KEY1
#define KEY1		(1<<8)
#define KEY1R		(KEY1|KEYR)
#define KEY1F		(KEY1|KEYF)
#define KEY1P		(KEY1|KEYP)
//KEY2
#define KEY2		(2<<8)
#define KEY2R		(KEY2|KEYR)
#define KEY2F		(KEY2|KEYF)
#define KEY2P		(KEY2|KEYP)
//KEY3
#define KEY3		(3<<8)
#define KEY3R		(KEY3|KEYR)
#define KEY3F		(KEY3|KEYF)
#define KEY3P		(KEY3|KEYP)
//KEY4
#define KEY4		(4<<8)
#define KEY4R		(KEY4|KEYR)
#define KEY4F		(KEY4|KEYF)
#define KEY4P		(KEY4|KEYP)

//------------------------------------------------------------------------------------------------//
// Configurations of TG Handlers
//------------------------------------------------------------------------------------------------//
#define TGR			0x10000000
#define TGF			0x20000000
#define TGP			0x40000000


//------------------------------------------------------------------------------------------------//
// Configurations of In-Out keys
//------------------------------------------------------------------------------------------------//
extern void Default_KeyHandler(UINT32 u32Param);


#define DECLARE_MATRIX_KEY() \
S_KEYPAD_KEY_HANDLER const g_asMatrixKeyHandler[] =  \
{  \
	{Default_KeyHandler, KEY1F, BIT10, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_FALLING}, \
	{Default_KeyHandler, KEY1R, BIT10, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_RISING}, \
	{Default_KeyHandler, KEY1P, BIT10, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_PRESSING}, \
	{Default_KeyHandler, KEY2F, BIT11, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_FALLING}, \
	{Default_KeyHandler, KEY2R, BIT11, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_RISING}, \
	{Default_KeyHandler, KEY2P, BIT11, BIT8, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_PRESSING}, \
	{Default_KeyHandler, KEY3F, BIT10, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_FALLING}, \
	{Default_KeyHandler, KEY3R, BIT10, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_RISING}, \
	{Default_KeyHandler, KEY3P, BIT10, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_PRESSING}, \
	{Default_KeyHandler, KEY4F, BIT11, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_FALLING}, \
	{Default_KeyHandler, KEY4R, BIT11, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_RISING}, \
	{Default_KeyHandler, KEY4P, BIT11, BIT9, KEYPAD_GPIOA, KEYPAD_GPIOB, KEYPAD_PRESSING}, \
	{0, 0, 0, 0, 0, 0, 0}  \
	}; \
	const UINT8 g_au8MatrixKeyStateIndex[] = {0};

#if (MATRIX_OUTPUT_PINS_COUNT>0)       // not create if MATRIX_KEY_COUNT==0
#define DECLARE_MATRIX_KEY_BUF()	UINT16 g_u16aKeyPinValueBuf[MATRIX_OUTPUT_PINS_COUNT];
#else
#define DECLARE_MATRIX_KEY_BUF()
#endif

//------------------------------------------------------------------------------------------------//

#define	DECLARE_TRIGGER_KEY() \
S_KEYPAD_TGR_HANDLER const g_asTriggerKeyHandler[] =  \
{ \
	{0, 0, 0, 0, 0}  \
	}; \
	const UINT8 g_au8TriggerKeyStateIndex[] = {0};


//%{CodeGen_Block_End}
	
extern void Default_KeyHandler(UINT32 u32Param);

//------------------------------------------------------------------------------------------------//
// Configurations of Touch Keys
//------------------------------------------------------------------------------------------------//
#define TOUCHR		0x10000000
#define TOUCHF		0x20000000
#define TOUCHP		0x40000000

// TOUCH1
#define TOUCH1 		(1)
#define TOUCH1R		(TOUCH1|TOUCHR)
#define TOUCH1F		(TOUCH1|TOUCHF)
#define TOUCH1P		(TOUCH1|TOUCHP)
// TOUCH2
#define TOUCH2 		(2)
#define TOUCH2R		(TOUCH2|TOUCHR)
#define TOUCH2F		(TOUCH2|TOUCHF)
#define TOUCH2P		(TOUCH2|TOUCHP)
// TOUCH3
#define TOUCH3 		(3)
#define TOUCH3R		(TOUCH3|TOUCHR)
#define TOUCH3F		(TOUCH3|TOUCHF)
#define TOUCH3P		(TOUCH3|TOUCHP)
// TOUCH4
#define TOUCH4 		(4)
#define TOUCH4R		(TOUCH4|TOUCHR)
#define TOUCH4F		(TOUCH4|TOUCHF)
#define TOUCH4P		(TOUCH4|TOUCHP)
// TOUCH5
#define TOUCH5 		(5)
#define TOUCH5R		(TOUCH5|TOUCHR)
#define TOUCH5F		(TOUCH5|TOUCHF)
#define TOUCH5P		(TOUCH5|TOUCHP)
// TOUCH6
#define TOUCH6 		(6)
#define TOUCH6R		(TOUCH6|TOUCHR)
#define TOUCH6F		(TOUCH6|TOUCHF)
#define TOUCH6P		(TOUCH6|TOUCHP)
	
#define TOUCH_KEY_COUNT			(0)

#define TOUCH_CLR_CAP_MASK		(SYS_GPB_MFP_PB0MFP_Msk|SYS_GPB_MFP_PB1MFP_Msk|SYS_GPB_MFP_PB2MFP_Msk|SYS_GPB_MFP_PB3MFP_Msk|SYS_GPB_MFP_PB6MFP_Msk|SYS_GPB_MFP_PB7MFP_Msk)
#define TOUCH_CFG_CAP_MASK		(SYS_GPB_MFP_PB0MFP_CMP0|SYS_GPB_MFP_PB1MFP_CMP1|SYS_GPB_MFP_PB2MFP_CMP2|SYS_GPB_MFP_PB3MFP_CMP3|SYS_GPB_MFP_PB6MFP_CMP6|SYS_GPB_MFP_PB7MFP_CMP7)
	
#define TOUCH_KEY_PINS_MASK		(BIT0|BIT1|BIT2|BIT3|BIT6|BIT7)
	
#define TOUCH_KEY_HANDLE_COUNT	(18)
	
#if( TOUCH_KEY_COUNT > 0 )
#define DECLARE_TOUCH_KEY() 								\
S_KEYPAD_TOUCH_HANDLER const g_asTouchKeyHandler[] =  		\
{  															\
	{Default_KeyHandler, TOUCH1F, BIT0, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH1R, BIT0, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH1P, BIT0, KEYPAD_PRESSING},	\
	{Default_KeyHandler, TOUCH2F, BIT1, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH2R, BIT1, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH2P, BIT1, KEYPAD_PRESSING},	\
	{Default_KeyHandler, TOUCH3F, BIT2, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH3R, BIT2, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH3P, BIT2, KEYPAD_PRESSING},	\
	{Default_KeyHandler, TOUCH4F, BIT3, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH4R, BIT3, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH4P, BIT3, KEYPAD_PRESSING},	\
	{Default_KeyHandler, TOUCH5F, BIT6, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH5R, BIT6, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH5P, BIT6, KEYPAD_PRESSING},	\
	{Default_KeyHandler, TOUCH6F, BIT7, KEYPAD_FALLING},	\
	{Default_KeyHandler, TOUCH6R, BIT7, KEYPAD_RISING},		\
	{Default_KeyHandler, TOUCH6P, BIT7, KEYPAD_PRESSING},	\
	{0,0,0,0}												\
	}; 														\
	const UINT8 g_au8TouchKeyStateIndex[] = {0};
#else
#define DECLARE_TOUCH_KEY() 		
#endif
	
#if ( TOUCH_KEY_HANDLE_COUNT > 0 && TOUCH_KEY_COUNT > 0 )   
#define DECLARE_TOUCH_KEY_BUF()	UINT16 g_u16aTouchPinValueBuf[TOUCH_KEY_HANDLE_COUNT]; 
#else
#define DECLARE_TOUCH_KEY_BUF()
#endif

#if ( TOUCH_KEY_COUNT > 0 )
#define DECLARE_TOUCH_THRESHOLD()							\
S_KEYPAD_TOUCH_THRESHOLD const KEYPAD_TOUCH_THRESHOLD[]= 	\
{															\
	{ 800, 350}, { 1200, 200}, { 750, 300}, { 800, 350},	\
	{ 800, 350}, { 750, 300}, { 800, 350}, { 1200, 200}		\
};
#else
#define DECLARE_TOUCH_THRESHOLD()
#endif

#endif
