#ifndef _SPIFLASHMAP_H_
#define _SPIFLASHMAP_H_

#define SPIFLASH_BLOCK_SIZE			4096
#define SPIFLASH_PAGE_SIZE			256

#define AUDIOROM_STORAGE_START_ADDR			0
#define TALKTOSINGAPP_STORAGE_START_ADDR	0
//#define STORAGE_END							(TALKTOSINGAPP_STORAGE_START_ADDR+TALKTOSINGAPP_STORAGE_SIZE)


#endif
